from typing import Tuple
from Cython import double
import numpy as np


def f_continuous(theta: double, v: double, mu: double) -> Tuple[double, double, double]: ...

def rk4_cy(x: double, y: double, theta: double, v: double, mu: double, dt: double) -> Tuple[double, double, double]: ...

def computeDistance(senderLatitude: float, senderLongitude: float, receiverLatitude: float, receiverLongitude: float) -> float: ...

def computeDistanceNoSqrt(senderLatitude: float, senderLongitude: float, receiverLatitude: float, receiverLongitude: float) -> float: ...

def shortest_path_length_cy(G: "np.typing.NDArray[np.uint8]", source: int) -> list[float]: ...

def warshall_cy(G: "np.typing.NDArray[np.uint8]") -> "np.typing.NDArray[np.uint8]": ...

def shortest_path_cy(G: "np.typing.NDArray[np.uint8]", source: int, target: int) -> list[int]: ...
